name:                plot
version:             0.2.2.0
github:              "weeezes/plot"
license:             BSD3
author:              "Vesa Hagström"
copyright:           "2018 Vesa Hagström"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/weeezes/plot#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- brick
- bytestring
- containers
- directory
- linear
- microlens
- microlens-th
- optparse-applicative
- random
- stm
- time
- unix
- vector
- vty
- word-wrap
- text

library:
  source-dirs: src

executables:
  plot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3 
    - -fexcess-precision
    - -optc-O3
    - -optc-ffast-math
    - -fforce-recomp
    - -optl-static
    - -optl-pthread
    dependencies:
    - plot

tests:
  plot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plot
    - HTF

benchmarks:
  plot-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plot
    - criterion
